apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name:  heroes-east
  labels:
    name:  heroes-east
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name:  heroes-east
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - image: <login_server>.azurecr.io/azureworkshop/rating-api:v1
        name:  ratings-api
        resources:
          requests:
            memory: 1G
            cpu: 1
        env:
        - name:  MONGODB_URI
          value:  <value from lab#8 - CosmosDB's connection string>
        ports:
        - containerPort:  3000
          name:  heroes-api
        imagePullPolicy: Always
      - image: <login_server>.azurecr.io/azureworkshop/rating-web:v1
        name:  ratings-web
        resources:
          requests:
            memory: 1G
            cpu: 1
        env:
        - name:  API
          value:  http://localhost:3000/
        - name: KUBE_NODE_NAME
          value: "East US"
        ports:
        - containerPort:  8080
          name:  heroes-web
        imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: virtual-kubelet-virtual-kubelet-linux-eastus
      tolerations:
      - key: azure.com/aci
        effect: NoSchedule
